version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - gb-beng
  assignees:
    - gb-beng
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  ignore:
  # Nuxt has it's own update mechanism:
  # https://github.com/nuxt/nuxt/blob/7b35a1fe4faed49fffe3427a0db4aabae138f4ae/docs/3.api/5.commands/upgrade.md
    - dependency-name: "nuxt"
