---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/en/labs
  label: Labs
  create: documents
  match: "**/*.md"
  templates:
  - lab
- type: directory
  path: content/en/projects
  label: Projects
  create: documents
  match: "**/*.md"
  templates:
  - project
- type: directory
  path: content/en/topics
  label: Topics
  create: documents
  match: "**/*.md"
- type: directory
  path: content/en/datasets
  label: Data sets
  create: documents
  match: "**/*.md"
  templates:
  - dataset
- type: directory
  path: content/en/apis
  label: APIs
  create: documents
  match: "**/*.md"
- type: directory
  path: content/en/blogs
  label: Blog Posts EN
  create: documents
  match: "**/*.md"
  templates:
  - blog-post
- type: directory
  path: content/nl/blogs
  label: Blog Posts NL
  create: documents
  match: "**/*.md"
  templates:
  - blog-post
- type: directory
  path: content/en/archive
  label: Archive
  create: documents
  match: "**/*.md"
- type: document
  path: content/en/about.md
  label: About EN
- type: document
  path: content/nl/about.md
  label: About NL
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
