export default {
  home: 'mdi-home',
  dataset: 'mdi-database',
  blog: 'mdi-post',
  topic: 'mdi-shape',
  lab: 'mdi-flask',
  api: 'mdi-power-plug',
  archive: 'mdi-archive',
  about: 'mdi-information',
  organization: 'mdi-domain',
  link: 'mdi-link-variant',
  download: 'mdi-download',
  email: 'mdi-email',
  license: 'mdi-license',
}
