---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: subtitle
  label: subtitle
- type: file
  name: image
  label: image
- type: list
  name: tags
  label: tags
- type: list
  name: datasets
  label: datasets
