---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: Title
  config:
    required: true
- type: text
  name: subtitle
  label: Subtitle
- type: file
  name: image
  label: Image
  config:
    maxSize: 2
  description: An image representing the project, preferably landscape orientation,
    max 2 MB
- type: list
  name: tags
  label: Tags
- type: list
  name: datasets
  label: Datasets
  config:
    use_select: true
    source:
      type: pages
      section: data-sets
